### ISSUE TITLE
Dft_16.mat not given

### ISSUE THREAD

**Issue by scar1708** [YuZhang-GitHub/Codebook_Learning_RL#1]
Sir,

I am unable to find the Dft_16.mat file in the repository. 
&
NameError: name 'dft_mtx' is not defined

Can you please help me?

Thank you.

**Comment by YuZhang-GitHub** [comment]
Hi,

You can simply use Matlab to generate such DFT matrix:

```
x = (1/sqrt(16)) * dftmtx(16);
save('Dft_16.mat', 'x')
```

Good luck.
